#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: notebook.ipynb

import numpy as np
import operator

def part_1_a():
    """Provide probabilities for the word HMMs outlined below.
    Word ALLIGATOR, NUTS, and SLEEP.
    Review Udacity Lesson 8 - Video #29. HMM Training
    Returns:
        tuple() of
        (prior probabilities for all states for word ALLIGATOR,
         transition probabilities between states for word ALLIGATOR,
         emission parameters tuple(mean, std) for all states for word ALLIGATOR,
         prior probabilities for all states for word NUTS,
         transition probabilities between states for word NUTS,
         emission parameters tuple(mean, std) for all states for word NUTS,
         prior probabilities for all states for word SLEEP,
         transition probabilities between states for word SLEEP,
         emission parameters tuple(mean, std) for all states for word SLEEP)
        Sample Format (not complete):
        (
            {'A1': prob_of_starting_in_A1, 'A2': prob_of_starting_in_A2, ...},
            {'A1': {'A1': prob_of_transition_from_A1_to_A1,
                    'A2': prob_of_transition_from_A1_to_A2,
                    'A3': prob_of_transition_from_A1_to_A3,
                    'Aend': prob_of_transition_from_A1_to_Aend},
             'A2': {...}, ...},
            {'A1': tuple(mean_of_A1, standard_deviation_of_A1),
             'A2': tuple(mean_of_A2, standard_deviation_of_A2), ...},
            {'N1': prob_of_starting_in_N1, 'N2': prob_of_starting_in_N2, ...},
            {'N1': {'N1': prob_of_transition_from_N1_to_N1,
                    'N2': prob_of_transition_from_N1_to_N2,
                    'N3': prob_of_transition_from_N1_to_N3,
                    'Nend': prob_of_transition_from_N1_to_Nend},
             'N2': {...}, ...}
            {'N1': tuple(mean_of_N1, standard_deviation_of_N1),
             'N2': tuple(mean_of_N2, standard_deviation_of_N2), ...},
            {'S1': prob_of_starting_in_S1, 'S2': prob_of_starting_in_S2, ...},
            {'S1': {'S1': prob_of_transition_from_S1_to_S1,
                    'S2': prob_of_transition_from_S1_to_S2,
                    'S3': prob_of_transition_from_S1_to_S3,
                    'Send': prob_of_transition_from_S1_to_Send},
             'S2': {...}, ...}
            {'S1': tuple(mean_of_S1, standard_deviation_of_S1),
             'S2': tuple(mean_of_S2, standard_deviation_of_S2), ...}
        )
        NOTE: As stated earlier in this notebook, any decimal numbers should be given to 3 decimal places. Any integers should be given as floats like '5.0'. If numbers are not given in this format, the tests will fail.
    """

    """Word ALLIGATOR"""
    # Prior probability for each word is 1/3
    a_prior_probs = {
        'A1': 0.333,
        'A2': 0.0,
        'A3': 0.0,
        'Aend': 0.0
    }
    a_transition_probs = {
        'A1': {'A1': 0.833, 'A2': 0.167, 'A3': 0.0, 'Aend': 0.0},
        'A2': {'A1': 0.0, 'A2': 0.667, 'A3': 0.333, 'Aend': 0.0},
        'A3': {'A1': 0.0, 'A2': 0.0, 'A3': 0.812, 'Aend': 0.188},
        'Aend': {'A1': 0.0, 'A2': 0.0, 'A3': 0.0, 'Aend': 1.0}
    }
    # Parameters for end state is not required
    a_emission_paras = {
        'A1': (51.056, 21.986),
        'A2': (21.333, 7.04),
        'A3': (49.75, 17.785),
        'Aend': (None, None)
    }

    """Word NUTS"""
    n_prior_probs = {
        'N1': 0.333,
        'N2': 0.0,
        'N3': 0.0,
        'Nend': 0.0
    }
    # Probability of a state changing to another state.
    n_transition_probs = {
        'N1': {'N1': 0.8, 'N2': 0.2, 'N3': 0.0, 'Nend': 0.0},
        'N2': {'N1': 0.0, 'N2': 0.885, 'N3': 0.115, 'Nend': 0.0},
        'N3': {'N1': 0.0, 'N2': 0.0, 'N3': 0.571, 'Nend': 0.429},
        'Nend': {'N1': 0.0, 'N2': 0.0, 'N3': 0.0, 'Nend': 1.0}
    }
    # Parameters for end state is not required
    n_emission_paras = {
        'N1': (30.667, 4.962),
        'N2': (43.192, 10.59),
        'N3': (61.714, 13.583),
        'Nend': (None, None)
    }

    """Word SLEEP"""
    s_prior_probs = {
        'S1': 0.333,
        'S2': 0.0,
        'S3': 0.0,
        'Send': 0.0
    }
    s_transition_probs = {
        'S1': {'S1': 0.625, 'S2': 0.375, 'S3': 0.0, 'Send': 0.0},
        'S2': {'S1': 0.0, 'S2': 0.864, 'S3': 0.136, 'Send': 0.0},
        'S3': {'S1': 0.0, 'S2': 0.0, 'S3': 0.0, 'Send': 1.0},
        'Send': {'S1': 0.0, 'S2': 0.0, 'S3': 0.0, 'Send': 1.0}
    }
    # Parameters for end state is not required
    s_emission_paras = {
        'S1': (29.5, 8.411),
        'S2': (36.182, 5.99),
        'S3': (36.667, 1.886),
        'Send': (None, None)
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def gaussian_prob(x, para_tuple):
    """Compute the probability of a given x value

    Args:
        x (float): observation value
        para_tuple (tuple): contains two elements, (mean, standard deviation)

    Return:
        Probability of seeing a value "x" in a Gaussian distribution.

    Note:
        We simplify the problem so you don't have to take care of integrals.
        Theoretically speaking, the returned value is not a probability of x,
        since the probability of any single value x from a continuous
        distribution should be zero, instead of the number outputted here.
        By definition, the Gaussian percentile of a given value "x"
        is computed based on the "area" under the curve, from left-most to x.
        The probability of getting value "x" is zero because a single value "x"
        has zero width, however, the probability of a range of value can be
        computed, for say, from "x - 0.1" to "x + 0.1".

    """
    if list(para_tuple) == [None, None]:
        return 0.0

    mean, std = para_tuple
    gaussian_percentile = (2 * np.pi * std**2)**-0.5 * \
                          np.exp(-(x - mean)**2 / (2 * std**2))
    return gaussian_percentile


def viterbi(evidence_vector, states, prior_probs,
            transition_probs, emission_paras):
    """Viterbi Algorithm to calculate the most likely states give the evidence.
    Args:
        evidence_vector (list): List of right hand Y-axis positions (integer).
        states (list): List of all states in a word. No transition between words.
                       example: ['A1', 'A2', 'A3', 'Aend', 'N1', 'N2', 'N3', 'Nend']
        prior_probs (dict): prior distribution for each state.
                            example: {'X1': 0.25,
                                      'X2': 0.25,
                                      'X3': 0.25,
                                      'Xend': 0.25}
        transition_probs (dict): dictionary representing transitions from each
                                 state to every other valid state such as for the above
                                 states, there won't be a transition from 'A1' to 'N1'
        emission_paras (dict): parameters of Gaussian distribution
                                from each state.
    Return:
        tuple of
        ( A list of states the most likely explains the evidence,
          probability this state sequence fits the evidence as a float )
    Note:
        You are required to use the function gaussian_prob to compute the
        emission probabilities.
    """

    # Handle empty evidence
    if not evidence_vector:
        return [], 0.0

    n = len(evidence_vector)

    # Initialize Viterbi table and backpointer table
    # viterbi[t][state] = max probability of being in state at time t
    viterbi_table = [{} for _ in range(n)]
    backpointer = [{} for _ in range(n)]

    # Initialization step (t=0)
    for state in states:
        prior = prior_probs.get(state, 0.0)
        emission = gaussian_prob(evidence_vector[0], emission_paras[state])
        viterbi_table[0][state] = prior * emission
        backpointer[0][state] = None

    # Recursion step (t=1 to n-1)
    for t in range(1, n):
        for curr_state in states:
            max_prob = 0.0
            max_prev_state = None

            # Find the best previous state
            for prev_state in states:
                trans_prob = transition_probs.get(prev_state, {}).get(curr_state, 0.0)
                emission = gaussian_prob(evidence_vector[t], emission_paras[curr_state])
                prob = viterbi_table[t-1][prev_state] * trans_prob * emission

                if prob > max_prob:
                    max_prob = prob
                    max_prev_state = prev_state

            viterbi_table[t][curr_state] = max_prob
            backpointer[t][curr_state] = max_prev_state

    # Termination step: find the best final state
    max_final_prob = 0.0
    best_final_state = None

    for state in states:
        if viterbi_table[n-1][state] > max_final_prob:
            max_final_prob = viterbi_table[n-1][state]
            best_final_state = state

    # Check if we found a valid path
    if max_final_prob == 0.0 or best_final_state is None:
        # No valid sequence found
        return [], 0.0

    # Backtrack to find the best path
    sequence = []
    current_state = best_final_state

    for t in range(n-1, -1, -1):
        sequence.insert(0, current_state)
        current_state = backpointer[t][current_state]

    probability = max_final_prob

    return sequence, probability

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def part_2_a():
    """Provide probabilities for the word HMMs outlined below.
    Now, at each time frame you are given 2 observations (right hand Y
    position & right thumb Y position). Use the result you derived in
    part_1_a, accompany with the provided probability for right thumb, create
    a tuple of (right-hand-y, right-thumb-y) to represent high-dimension transition &
    emission probabilities.
    """

    # Get Part 1a results for right hand Y
    (a_prior_1a, a_trans_1a, a_emis_1a,
     n_prior_1a, n_trans_1a, n_emis_1a,
     s_prior_1a, s_trans_1a, s_emis_1a) = part_1_a()

    """Word ALLIGATOR"""
    a_prior_probs = a_prior_1a

    # Transition probs: same for both dimensions
    a_transition_probs = {
        'A1': {'A1': (0.833, 0.833), 'A2': (0.167, 0.167), 'A3': (0.0, 0.0), 'Aend': (0.0, 0.0)},
        'A2': {'A1': (0.0, 0.0), 'A2': (0.667, 0.667), 'A3': (0.333, 0.333), 'Aend': (0.0, 0.0)},
        'A3': {'A1': (0.0, 0.0), 'A2': (0.0, 0.0), 'A3': (0.812, 0.812), 'Aend': (0.188, 0.188)},
        'Aend': {'A1': (0.0, 0.0), 'A2': (0.0, 0.0), 'A3': (0.0, 0.0), 'Aend': (1.0, 1.0)}
    }

    # Emission params: [(right-hand-mean, right-hand-std), (right-thumb-mean, right-thumb-std)]
    a_emission_paras = {
        'A1': [(51.056, 21.986), (53.529, 17.493)],
        'A2': [(21.333, 7.04), (40.769, 6.104)],
        'A3': [(49.75, 17.785), (51.0, 12.316)],
        'Aend': [(None, None), (None, None)]
    }

    """Word NUTS"""
    n_prior_probs = n_prior_1a

    n_transition_probs = {
        'N1': {'N1': (0.8, 0.8), 'N2': (0.2, 0.2), 'N3': (0.0, 0.0), 'Nend': (0.0, 0.0)},
        'N2': {'N1': (0.0, 0.0), 'N2': (0.885, 0.885), 'N3': (0.115, 0.115), 'Nend': (0.0, 0.0)},
        'N3': {'N1': (0.0, 0.0), 'N2': (0.0, 0.0), 'N3': (0.571, 0.571), 'Nend': (0.429, 0.429)},
        'Nend': {'N1': (0.0, 0.0), 'N2': (0.0, 0.0), 'N3': (0.0, 0.0), 'Nend': (1.0, 1.0)}
    }

    n_emission_paras = {
        'N1': [(30.667, 4.962), (36.318, 7.376)],
        'N2': [(43.192, 10.59), (60.0, 15.829)],
        'N3': [(61.714, 13.583), (37.476, 8.245)],
        'Nend': [(None, None), (None, None)]
    }

    """Word SLEEP"""
    s_prior_probs = s_prior_1a

    s_transition_probs = {
        'S1': {'S1': (0.625, 0.625), 'S2': (0.375, 0.375), 'S3': (0.0, 0.0), 'Send': (0.0, 0.0)},
        'S2': {'S1': (0.0, 0.0), 'S2': (0.864, 0.864), 'S3': (0.136, 0.136), 'Send': (0.0, 0.0)},
        'S3': {'S1': (0.0, 0.0), 'S2': (0.0, 0.0), 'S3': (0.0, 0.0), 'Send': (1.0, 1.0)},
        'Send': {'S1': (0.0, 0.0), 'S2': (0.0, 0.0), 'S3': (0.0, 0.0), 'Send': (1.0, 1.0)}
    }

    s_emission_paras = {
        'S1': [(29.5, 8.411), (35.357, 7.315)],
        'S2': [(36.182, 5.99), (31.462, 5.048)],
        'S3': [(36.667, 1.886), (38.333, 7.409)],
        'Send': [(None, None), (None, None)]
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def multidimensional_viterbi(evidence_vector, states, prior_probs,
                             transition_probs, emission_paras):
    """Decode the most likely word phrases generated by the evidence vector.
    States, prior_probs, transition_probs, and emission_probs will now contain
    all the words from part_2_a.
    Evidence vector is a list of tuples where the first element of each tuple is the right
    hand coordinate and the second element is the right thumb coordinate.
    """

    # Handle empty evidence
    if not evidence_vector:
        return [], 0.0

    n = len(evidence_vector)

    # Initialize Viterbi table and backpointer table
    viterbi_table = [{} for _ in range(n)]
    backpointer = [{} for _ in range(n)]

    # Initialization step (t=0)
    for state in states:
        prior = prior_probs.get(state, 0.0)

        # For multidimensional observations, compute emission for each dimension
        # evidence_vector[0] is (right_hand_y, right_thumb_y)
        emission_params_list = emission_paras[state]

        # Calculate emission probability for each dimension and multiply
        emission_prob = 1.0
        for dim_idx, obs_val in enumerate(evidence_vector[0]):
            emission_prob *= gaussian_prob(obs_val, emission_params_list[dim_idx])

        viterbi_table[0][state] = prior * emission_prob
        backpointer[0][state] = None

    # Recursion step (t=1 to n-1)
    for t in range(1, n):
        for curr_state in states:
            max_prob = 0.0
            max_prev_state = None

            # Find the best previous state
            for prev_state in states:
                # Get transition probability (use first element of tuple, they should be same)
                trans_prob_tuple = transition_probs.get(prev_state, {}).get(curr_state, (0.0, 0.0))
                trans_prob = trans_prob_tuple[0]  # Both dimensions have same transition prob

                # Calculate emission probability for current observation
                emission_params_list = emission_paras[curr_state]
                emission_prob = 1.0
                for dim_idx, obs_val in enumerate(evidence_vector[t]):
                    emission_prob *= gaussian_prob(obs_val, emission_params_list[dim_idx])

                prob = viterbi_table[t-1][prev_state] * trans_prob * emission_prob

                if prob > max_prob:
                    max_prob = prob
                    max_prev_state = prev_state

            viterbi_table[t][curr_state] = max_prob
            backpointer[t][curr_state] = max_prev_state

    # Termination step: find the best final state
    max_final_prob = 0.0
    best_final_state = None

    for state in states:
        if viterbi_table[n-1][state] > max_final_prob:
            max_final_prob = viterbi_table[n-1][state]
            best_final_state = state

    # Check if we found a valid path
    if max_final_prob == 0.0 or best_final_state is None:
        # No valid sequence found
        return [], 0.0

    # Backtrack to find the best path
    sequence = []
    current_state = best_final_state

    for t in range(n-1, -1, -1):
        sequence.insert(0, current_state)
        current_state = backpointer[t][current_state]

    probability = max_final_prob

    return sequence, probability

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def return_your_name():
    """Return your name
    """
    return "Yiqian Zhang"
